# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WorkfloPlus Docs
email: info@intoware.com
description: >- # this means to ignore newlines until "baseurl:"
  WorkfloPlus Documentation for Developers. Simple guides and reference material
  for extracting data from your WorfkloPlus Team.
baseurl: "/workfloplus-docs" # the subpath of your site, e.g. /blog
url: "https://intoware.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: intoware
github_username:  intoware

product_name: WorkfloPlus
company_name: Intoware
support_url: https://help.workfloplus.com

accounts_api_base_url: https://accounts.workfloplus.com/api
main_api_base_url: https://gateway.workfloplus.com
dashboard_base_url: https://dashboard.workfloplus.com
policies_base_url: https://www.workfloplus.com/auth

# Build settings
markdown: kramdown
color_scheme: foo
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Aux links for the upper right navigation
aux_links:
  "WorkfloPlus Documentation on GitHub":
    - "//github.com/intoware/workfloplus-docs"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

footer_content: "Copyright &copy; 2021 Intoware Limited."

logo: assets/logo.png
